/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M9
 * Generated at: 2016-09-03 05:22:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.nbaplayer.*;

public final class readDB_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.nbaplayer");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Famous NBA Players</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"player.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\r\n");
      out.write("\t\t<h1>Famous NBA Players in History</h1>\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<main>\r\n");
      out.write("\r\n");
      out.write("\t<h2>A Brief History of the National Basketball Association</h2>\r\n");
      out.write("\r\n");
      out.write("\t<p>The National Basketball Association (NBA) is one of the most\r\n");
      out.write("\t\timportant professional sport league in North America. The NBA\r\n");
      out.write("\t\twas founded in 1946 in New York City, New York. The NBA has 30 \r\n");
      out.write("\t\tteams which are all based in the United States except for the \r\n");
      out.write("\t\tToronto Raptors which is based in Canada. Over the years, a lot \r\n");
      out.write("\t\tof the NBA players have amassed lots of wealth because they are \r\n");
      out.write("\t\tpaid handsomely. Its been 60 years now since the founding of the \r\n");
      out.write("\t\tNBA and over that period of time, a lot of the players have become \r\n");
      out.write("\t\tso famous for being one of the greatest basketball players.</p>\r\n");
      out.write("\r\n");
      out.write("\t<h2>List of Some of the Famous NBA Players</h2>\r\n");
      out.write("\r\n");
      out.write("\t<p>There are so many great and famous NBA players. Some of those\r\n");
      out.write("\t\tplayers achieved their greatness on the basketball court while others\r\n");
      out.write("\t\tdo so outside of the basketball court by the impact they have on the\r\n");
      out.write("\t\tworld.</p>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<p>Please <a hreflang=\"\">click here</a> to see a list of some of the famous NBA\r\n");
      out.write("\t\tplayers.</p>\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<table class=\"table table-striped\";\">\r\n");
      out.write("\t");
 DAO.readFromDB(); 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>Player ID</th>\r\n");
      out.write("\t\t\t<th>First Name</th>\r\n");
      out.write("\t\t\t<th>Last Name</th>\r\n");
      out.write("\t\t\t<th>Current or Last Team</th>\r\n");
      out.write("\t\t\t<th>Position</th>\r\n");
      out.write("\t\t\t<th>Total Points</th>\r\n");
      out.write("\t\t\t<th>Championships Won</th>\r\n");
      out.write("\t\t\t<th>MVP Won</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

		Player readToJSP = new Player();
		for (int i = 0; i < DAO.famousPlayers.size(); i++) {
			readToJSP = DAO.famousPlayers.get(i);
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print( readToJSP.getPlayerID() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( readToJSP.getFirstName() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( readToJSP.getLastName() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( readToJSP.getCurrentLastTeam() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( readToJSP.getPosition() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( readToJSP.getTotalPoints() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( readToJSP.getChampionshipsWon() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( readToJSP.getMvpWon() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t");
 DAO.famousPlayers.clear(); 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div><br>\r\n");
      out.write("\t<img alt=\"Kareem Abdul-Jabbar\" src=\"images/Abdul_Jabbar.jpg\" width=\"200px\" height=\"200px\"> \r\n");
      out.write("\t<img alt=\"Larry Bird\" src=\"images/Larry_Bird.jpg\" width=\"200px\" height=\"200px\">\r\n");
      out.write("\t<img alt=\"Michael Jordan\" src=\"images/Jordan.jpg\" width=\"200px\" height=\"200px\">\r\n");
      out.write("\t<img alt=\"Shaquille O'Neal\" src=\"images/Shaquille_O'Neal.jpg\" width=\"200px\" height=\"200px\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</main>\r\n");
      out.write("\t<aside>\r\n");
      out.write("\t\t<h3>Famous NBA Player Recommendation Form</h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<p>Please use the form below to recommend an NBA player employee\r\n");
      out.write("\t\t\tthat you would like to be included in the Famous NBA players list.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"addToDB\" method=\"post\">\r\n");
      out.write("\t\t\tFirst name:<br> <input type=\"text\" name=\"first_name\"><br>\r\n");
      out.write("\t\t\tLast name:<br> <input type=\"text\" name=\"last_name\"><br>\r\n");
      out.write("\t\t\tCurrent or Last Team:<br> <input type=\"text\"\r\n");
      out.write("\t\t\t\tname=\"current_last_team\"><br> Position:<br> <input\r\n");
      out.write("\t\t\t\ttype=\"text\" name=\"position\"><br> Total Points:<br>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"total_points\"><br>\r\n");
      out.write("\t\t\tChampionships Won:<br> <input type=\"text\"\r\n");
      out.write("\t\t\t\tname=\"championships_won\"><br> MVP Won:<br> <input\r\n");
      out.write("\t\t\t\ttype=\"text\" name=\"mvp_won\"><br> <input type=\"submit\"\r\n");
      out.write("\t\t\t\tvalue=\"Submit\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t<h3>Famous NBA Player Update Form</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t<p>Please use the form below to update the information on a famous\r\n");
      out.write("\t\t\tNBA player.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"updatePlayer\" method=\"post\">\r\n");
      out.write("\t\t\tPlayer ID:<br> <input type=\"text\" name=\"player_id\"><br>\r\n");
      out.write("\t\t\tFirst name:<br> <input type=\"text\" name=\"first_name\"><br>\r\n");
      out.write("\t\t\tLast name:<br> <input type=\"text\" name=\"last_name\"><br>\r\n");
      out.write("\t\t\tCurrent or Last Team:<br> <input type=\"text\"\r\n");
      out.write("\t\t\t\tname=\"current_last_team\"><br> Position:<br> <input\r\n");
      out.write("\t\t\t\ttype=\"text\" name=\"position\"><br> Total Points:<br>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"total_points\"><br>\r\n");
      out.write("\t\t\tChampionships Won:<br> <input type=\"text\"\r\n");
      out.write("\t\t\t\tname=\"championships_won\"><br> MVP Won:<br> <input\r\n");
      out.write("\t\t\t\ttype=\"text\" name=\"mvp_won\"><br> <input type=\"submit\"\r\n");
      out.write("\t\t\t\tvalue=\"Submit\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t<h3>Famous NBA Player Deletion Form</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t<p>Please use the form below to delete the name of a famous NBA\r\n");
      out.write("\t\t\tplayer from the list of the Famous NBA players.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"deletePlayer\" method=\"post\">\r\n");
      out.write("\t\t\tPlayer ID:<br> <input type=\"text\" name=\"player_id\"><br>\r\n");
      out.write("\t\t\t  <input type=\"submit\" value=\"Submit\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</aside>\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tFor more information and pictures about the Famous NBA Players,\r\n");
      out.write("\t\t\tplease <a href=\"https://en.wikipedia.org/wiki/National_Basketball_Association/\"\r\n");
      out.write("\t\t\t\ttarget=\"_blank\">click here.</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
